from pathlib import Path

from envrctl import EnvrctlConfig
from envrctl.constants import DIRENV_RC

TEMPLATE = """
# Autogenerated by envrctl
{%- for key, value in vars.items() %}
export {{ key }}="{{ value }}"
{%- endfor %}
{%- for key, value in secrets.items() %}
export {{ key }}="$({{ secret_command }} {{ value }})"
{%- endfor %}
{%- for layout in layouts %}
layout {{ layout }}
{%- endfor %}
{%- for u in uses %}
use {{ u }}
{%- endfor %}
{%- if dotenv_if_exists %}
dotenv_if_exists
{%- endif %}
""".strip()


class DirenvConfig(EnvrctlConfig):
    def __init__(self) -> None:
        super().__init__()
        self.path = Path.cwd() / DIRENV_RC
        self.template = TEMPLATE
