from pathlib import Path

from envrctl import EnvrctlConfig
from envrctl.constants import PSENV_RC

TEMPLATE = """
# Autogenerated by envrctl
{%- for key, value in vars.items() %}
Set-Item env:{{ key }} "{{ value }}"
{%- endfor %}
{%- for key, value in secrets.items() %}
Set-Item env:{{ key }} "$({{ secret_command }} {{ value }})"
{%- endfor %}
""".strip()


class PsenvConfig(EnvrctlConfig):
    def __init__(self) -> None:
        super().__init__()
        self.path = Path.cwd() / PSENV_RC
        self.template = TEMPLATE
